### ISSUE TITLE
Dependency on react-native is tied to a specific version

### ISSUE THREAD

**Issue by jh3141** [gitboss2000/react-native-swipeable-flat-list#12]
The version of react-native requested by package.json is `^0.44.0`, which given that react-native updates the minor version on a monthly basis is too restrictive.  I'd suggest '>=0.44 <1' as a more appropriate version restriction.

**Comment by nshid** [comment]
You can easily change this requirement in your _node_modules_ folder. Otherwise, submit a pull request so the owner can review and include these changes.

**Comment by gitboss2000** [comment]
Please read [npm semver doc](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004)
