### ISSUE TITLE
How can I update a specific item in flatList once the list is loaded ?

### ISSUE THREAD

**Issue by koolkarni** [gitboss2000/react-native-swipeable-flat-list#14]
I wanted to update the List based on the 'address' and attach more 
codes to it
like:

if(address=='xyz'){
code= code+newCode;
} 

`

<SwipeableFlatList

                extraData={this.state}

                data={this.state.TESTDATA}

                keyExtractor={(item, index) => item.Code.toString()}
                renderItem={({ item}) => (
                    <TouchableOpacity
                        onPress={() => console.log('pressed TouchableOpacity')}
                        style={{
                            height: 75,
                        }}
                    >
                        <View style={styles.listItem}>

                            <Text style={styles.baseText}>
                                Stop Address: {item.Address}{'\n'}
              codes:    {item.Code}
                            </Text>
                        </View>
                    </TouchableOpacity>
                )}

            />

`

**Comment by gitboss2000** [comment]
I think, I don't quite understand your question. The `renderItem` prop accepts a function returning a Component.

Maybe this snippets helps?
```javascript
<SwipeableFlatList
    // ...
    renderItem={({item}) => {
        let code;
        if (item.Address === 'xyz') {
            code = code+newCode;
        }
        return (
            <TouchableOpacity
                // ...
            >
                <View style={styles.listItem}>
                    <Text style={styles.baseText}>
                            Stop Address: {item.Address}{'\n'}
          codes:    {item.Code}
                    </Text>
                </View>
            </TouchableOpacity>
        );
    }}
/>
```
