### ISSUE TITLE
Center component is being shrunk instead of going to left

### ISSUE THREAD

**Issue by Suresh-R-S** [gitboss2000/react-native-swipeable-flat-list#2]
Hi,

I have a center component which shows data like name, address etc.
When I swipe right the center component gets shrunk rather than the part of component hiding to left.
How can I achieve this?

**Comment by gitboss2000** [comment]
Hey,

if I understand you correctly, it is working as intended.
I had to make a choice between either moving the main/center component to the side or shrinking it, which I found to feel more natural and, therefore, I went with this approach.
