### ISSUE TITLE
getting naming collision on CRNA . cant start packager

### ISSUE THREAD

**Issue by yash2code** [gitboss2000/react-native-swipeable-flat-list#3]
est-haste-map: @providesModule naming collision:
 Duplicate module name: getHostComponentFromComposite
 Paths: E:\reactNative\shake\node_modules\react-native-swipeable-flat-list\node_modules\react-native\Libraries\Renderer
src\renderers\shared\stack\reconciler\getHostComponentFromComposite.js collides with E:\reactNative\shake\node_modules\
eact-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\getHostComponentFromComposite.js

his warning is caused by a @providesModule declaration with the same name across two different files.
est-haste-map: @providesModule naming collision:
 Duplicate module name: Transaction
 Paths: E:\reactNative\shake\node_modules\react-native-swipeable-flat-list\node_modules\react-native\Libraries\Renderer
src\renderers\shared\stack\reconciler\Transaction.js collides with E:\reactNative\shake\node_modules\react-native\Libra
ies\Renderer\src\renderers\shared\stack\reconciler\Transaction.js

his warning is caused by a @providesModule declaration with the same name across two different files.
est-haste-map: @providesModule naming collision:
 Duplicate module name: ResponderEventPlugin
 Paths: E:\reactNative\shake\node_modules\react-native-swipeable-flat-list\node_modules\react-native\Libraries\Renderer
src\renderers\shared\shared\event\eventPlugins\ResponderEventPlugin.js collides with E:\reactNative\shake\node_modules\
eact-native\Libraries\Renderer\src\renderers\shared\shared\event\eventPlugins\ResponderEventPlugin.js

his warning is caused by a @providesModule declaration with the same name across two different files.

**Comment by gitboss2000** [comment]
This should be fixed now.
