### ISSUE TITLE
Doesn't provide uid or index 

### ISSUE THREAD

**Issue by amitbravo** [gitboss2000/react-native-swipeable-flat-list#9]
my data does not contain a key or unique id for some reason, if array index replace it , would be really helpful , however, fileName is kind of unique in my data so how would I use it as alternate of key ?
Earlier I though may be array index(uid) as I see in a .map can be replaced such as : 
````
<SwipeableFlatList
data={this.state.selectedimages}
renderItem={({ item, uid }) => (
<View key={'avatar_'+uid} style={{ width: 200, height: 60}}><Text>{item.fileName} </Text></View>
)} 
renderRight={({ item, uid }) => (
<View key={'employee_'+uid} style={{ flexDirection: 'row', width: 100, height: 50,  justifyContent: 'center', alignItems: 'center'  }}>
<TouchableOpacity>
<Text>Edit</Text>
</TouchableOpacity>
<TouchableOpacity>
<Text>Delete</Text>
</TouchableOpacity>
  </View>
)}
backgroundColor={'white'}
/>
````

**Comment by nshid** [comment]
If you want to use a custom key for your list, set it using the **keyExtractor** prop:

    <SwipeableFlatList
        ref={(swipeableFlatList) => { this.swipeableFlatList = swipeableFlatList; }}
        data={flatListData}
        keyExtractor={item => item.fileName}
        ...

**Comment by gitboss2000** [comment]
> If you want to use a custom key for your list, set it using the **keyExtractor** prop:
> 
> ```
> <SwipeableFlatList
>     ref={(swipeableFlatList) => { this.swipeableFlatList = swipeableFlatList; }}
>     data={flatListData}
>     keyExtractor={item => item.fileName}
>     ...
> ```

This
